=== laurentmor/Site-perso/XMLBlog/src/test/resources/blog-resources/blog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Blog" type="BlogType">
    <xs:annotation>
      <xs:documentation>
  ~ Copyright (c) 2024
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  ~
  ~
  suppress XmlHighlighting, XmlHighlighting </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="CategoryType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="ID" use="required"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="description" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="CommentType">
    <xs:sequence>
      <xs:element type="xs:string" name="CommentText"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="ID"/>
    <xs:attribute type="xs:string" name="author"/>
    <xs:attribute type="xs:string" name="date"/>
    <xs:attribute type="xs:string" name="entryID"/>
    <xs:attribute type="xs:string" name="webPage"/>
  </xs:complexType>
  <xs:complexType name="EntryType">
    <xs:sequence>
      <xs:element type="CommentType" name="Comment"/>
      <xs:element type="xs:string" name="Resume"/>
      <xs:element type="xs:string" name="Text"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="ID"/>
    <xs:attribute type="xs:string" name="allowComments"/>
    <xs:attribute type="xs:string" name="categoryID"/>
    <xs:attribute type="xs:string" name="date"/>
  </xs:complexType>
  <xs:complexType name="BlogType">
    <xs:sequence>
      <xs:element type="CategoryType" name="Category" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="EntryType" name="Entry"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== laurentmor/Site-perso/XMLBlog/src/test/resources/blog-resources/blog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2024
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  ~
  ~
  -->
<!--suppress XmlHighlighting, XmlHighlighting -->

<Blog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="blog.xsd">
  <Category ID="ID_1222333" name="test"/>
  <Category ID="ID_320524799" description="" name="added"/>


  <Category ID="ID_-492027613" description="" name="remove"/>

  <Entry ID="ID_152369776" allowComments="false" categoryID="ID_1222333" date="2004-09-09">

    <Comment ID="ID_1476476016" author="Mike" date="Mon Nov 23 00:00:00 EST 2009"
      entryID="ID_152369776"
      webPage="no page">
      <CommentText>Hi HI</CommentText>
    </Comment>
    <Resume>
      feed
    </Resume>
    <Text>
      test entry !
    </Text>
  </Entry>

</Blog>
